### ISSUE TITLE
Publish package from dangersystems npm account

### ISSUE THREAD

**Issue by macklinu** [danger/generator-danger-plugin#19]
Right now, each `fix` or `feat` commit merged to master will ship a new version of this plugin (per semantic-release). The [npm package](https://www.npmjs.com/package/generator-danger-plugin) is published under my name. I've added dangersystems and orta as collaborators, though.

@orta is there anything we should do to change ownership on npm? Do we just need to swap my NPM_TOKEN in the Travis build settings with dangersystems NPM_TOKEN, or is this dangerous territory?

**Comment by orta** [comment]
I think it's totally fine for it to ship from yours 👍

**Comment by macklinu** [comment]
Cool 👍 closing this then
