### ISSUE TITLE
Fix creation script, update release script and upgrade dependencies

### ISSUE THREAD

**Issue by sogame** [danger/generator-danger-plugin#25]
Hi, I'm trying to create a new Danger JS plugin, but when running this generator, I get this error at the end:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Transform.Writable.write (_stream_writable.js:287:5)
```

Files and folders are created, but maybe something will be missing?

Might be due to something wrong in my local environment (I'm running node 8.11.2 and npm 5.10.0), but I noticed the project hasn't been updated for a long time, so maybe it's due to being a bit outdated 😅 

Also, after running `npm install` (I've selected to build the npm version without TypeScript) I get this warnings:

```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

Finally, I've also seen that the dependencies installed are a bit outdated, so it would be nice to upgrade to the latest versions :-P

Could you look into those issues? 😇 

Many thanks,
Sogame

**Comment by orta** [comment]
> Could you look into those issues? 😇

Thanks for letting us know, you're welcome to take a look at this, my main focus is working on Peril at the moment.

**Comment by sogame** [comment]
Hi @orta ,

I'll try, although I can't promise anything 😅 I've no experience with Yeoman templates nor publishing npm packages, but I'll try to take a look at it once back from holidays

**Comment by rohit-smpx** [comment]
I was trying to make a plugin, will try to fix this too. Might need to modify some things as some dependencies have had major releases with breaking changes.
